use_frameworks!

target 'SwiftRealmGridController' do
  pod 'RealmSwift', '>=0.96'
  pod 'SwiftFetchedResultsController', '>=2.4.3'
  pod 'TOWebViewController'
  pod 'HanekeSwift'
  pod 'RealmSwiftNYTStories'
end

target 'SwiftRealmGridControllerTests' do
  pod 'RealmSwift', '>=0.96'
end

