# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ABFRealmGridControllerExample' do
  pod "Realm", '>=0.100.0'
  pod "RBQFetchedResultsController", '>=4.0.3'
  pod 'TOWebViewController'
  pod 'Haneke', '~> 1.0'
  pod 'RealmNYTStories', '>=1.2'
end

target 'ABFRealmGridControllerExampleTests' do
  pod 'Realm/Headers', '>=0.100.0'
end

