# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ABFRealmGridControllerExample' do
  pod "Realm"
  pod "RBQFetchedResultsController"
end

target 'ABFRealmGridControllerExampleTests' do
  pod 'Realm/Headers'
end

