# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ABFRealmGridControllerExample' do
  pod "Realm", '>=0.96'
  pod "RBQFetchedResultsController"
  pod 'TOWebViewController'
  pod 'Haneke', '~> 1.0'
  pod 'RealmNYTStories'
end

target 'ABFRealmGridControllerExampleTests' do
  pod 'Realm/Headers', '>=0.96'
end

